### ISSUE TITLE
scalaz doesn't compile in what will soon become Scala 2.13.0-M3

### ISSUE THREAD

**Issue by SethTisue** [scalaz/scalaz#1629]
the compilation errors are in the `coreJVM` project. the full log is at https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/902/consoleFull

sample error (from a bunch of similar ones):

```
[scalaz] [error]  both method writerTraverse in class WriterTInstances1 of type [W]=> scalaz.Traverse[[β$19$]scalaz.WriterT[[X]X,W,β$19$]]
[scalaz] [error]  and method writerTTraverse in class WriterTInstances0 of type [F[_], W](implicit F0: scalaz.Traverse[F])scalaz.Traverse[[γ$22$]scalaz.WriterT[F,W,γ$22$]]
[scalaz] [error]  match expected type scalaz.Functor[[β$6$]scalaz.WriterT[[X]X,E,β$6$]]
[scalaz] [error]     new Adjunction[Writer[E, ?], Reader[E, ?]] {
[scalaz] [error]         ^
```

I'm not sure what this is about. I don't understand your source code, you don't know what changed in 2.13... we'll have to try to meet in the middle somewhere. getting the ball rolling with this ticket

until this is resolved, I have to remove scalaz from the 2.13 community build (this is happening at https://github.com/scala/community-builds/pull/673), which takes out a ton of downstream projects, too.

**Comment by SethTisue** [comment]
P.S. the errors look similar to errors in Shapeless, seen in the same log, so it's possible that when @milessabin looks into that, what he learns will be relevant here as well

**Comment by TomasMikula** [comment]
My guess is that it is because of https://github.com/scala/scala/pull/6069, which thanks to better unification resolves more implicits.

It will be problematic to make the same code compile with both Scala 2.11 and Scala 2.13. 😕

**Comment by SethTisue** [comment]
but #6069 was in 2.12.4...?

**Comment by TomasMikula** [comment]
Yes, but only under the flag `-Xsource:2.13`, which I don't see enabled in scalaz build.

**Comment by SethTisue** [comment]
ahhhhh, right.

**Comment by TomasMikula** [comment]
In the past, we enabled `-Ypartial-unification` and dropped 2.10 support in [one commit](https://github.com/scalaz/scalaz/pull/1367).

I personally would be fine with dropping 2.11 support in scalaz 7.3.x. But then, the community build uses 7.2.x anyway.

**Comment by TomasMikula** [comment]
Never mind, my guess must be wrong, since scalaz-core compiles with Scala 2.12.4 with `-Xsource:2.13`. Must be something else.

**Comment by SethTisue** [comment]
note that you should be able to reproduce the problem locally by using `publishLocal` to publish `scalacheck` and `kind-projector` for the latest Scala 2.13 nightly which at the moment is `2.13.0-pre-8eb67ed` (see https://stackoverflow.com/a/40622879/86485 for instructions on how to use Scala nightlies)

**Comment by xuwei-k** [comment]
workaround (Maybe break source compatibility, but keep binary compatibility)
https://github.com/xuwei-k/scalaz/commit/c186c59efdf20aa31781b41d452a8321ef52b1b7

**Comment by joroKr21** [comment]
It's probably scala/scala#6123. It makes `WriterT[Id, W, A] <:< WriterT[F, W, A] forSome { type F[_] }` (which indeed it should be). That means some implicits have to be moved around (or can be deleted altogether). I will try with `publishLocal` later if someone doesn't beat me to it.

**Comment by joroKr21** [comment]
There seem to be many such cases that I would deem "implicit priority inversion". For example `Trampoline` is a concrete instance of `Free` yet the `Monad` instance for `Trampoline` is defined in a superclass of the `Monad` instance for `Free`. Another example is the `MonadError` instance for `EitherT` being defined in a superclass of the `Monad` instance for `EitherT`, although `MonadError` is a subclass of `Monad`.

I don't know if it's possible to reorder everything in a binary compatible way (where is MiMa?). `8.x` shouldn't have this problem since it doesn't use typeclass inheritance.

**Comment by joroKr21** [comment]
#1632

**Comment by xuwei-k** [comment]
fixed in 7.2.x branch https://github.com/scalaz/scalaz/pull/1636
I'll merge #1632 and/or forwardport #1636 to 7.3
